[project]
name = "knn-vc"
version = "0.1.0"
description = ""
authors = [
    {name = "Peter Huang",email = "petersuper03@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<3.15"
dependencies = [
    "transformers (>=5.1.0,<6.0.0)",
    "torch (>=2.10.0,<3.0.0)",
    "torchaudio (>=2.10.0,<3.0.0)",
    "protobuf (>=6.33.5,<7.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "torchcodec (>=0.10.0,<0.11.0)",
    "pydantic-settings (>=2.13.1,<3.0.0)",
    "torchvision (>=0.25.0,<0.26.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
